#
#   ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#  ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#  ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#  ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#  ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#   ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
config:
  # Enable or disable maintenance mode.
  # You can change this option while /nxsm on/off command
  enable: true
  # Print message to kick player.
  kick-message:
    - '&8[&cNoxus Team&8]'
    - '&r'
    - '&c¡Server in maintenance!'
    - '&r'
    - '&aPlease, go to discord'
    - '&r'
    - '&eMore info in: &cYourDiscord'
  # Player that bypass maintenance mode
  player-maintenance:
    - Jonakls
    - zlPatrik_
    - md_5
