#
#   ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#  ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#  ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#  ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#  ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#   ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
config:
  # Enable or disable maintenance mode.
  # You can change this option using the /nxsm [on/off] command in-game.
  enable: false
  # Message sent to the player when attempting to connect while on
  # maintenance mode.
  kick-message:
    - '&8[&cNoxus Team&8]'
    - '&r'
    - '&c¡Server is currently under maintenance!'
    - '&r'
    - '&aYou can check our Discord server for'
    - '&amaintenance updates.'
    - '&r'
    - '&eMore info in: &chttps://discord.gg/invite'
  # Whitelisted players
  # (Players that can join the server under maintenance mode)
  whitelist-player:
    - Jonakls
    - zlPatrik_
    - md_5
