name: NoxusMaintenance
version: ${project.version}
main: org.noxus.noxusmaintenance.NoxusMaintenance
api-version: 1.16
authors: [ Jonakls ]
description: Basic maintenance plugin of server
commands:
  noxusmaintenance:
    aliases: ["nxm", "maintenance", "nm"]
